<!-- Dummy stuff -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xs-12">&nbsp;</div>
    </div>
</div>
<!-- Dummy stuff -->
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <form action="/search" role="search" method="GET" id="search">
                <div class="row">
                    <div class="col-xs-4">
                        <input type="text" name="q" class="typeahead form-control" placeholder="Search for...">
                        <?php if ($this->searchType !== NULL || $this->searchType !== "") : ?>
                        <input type="hidden" name="t" value="<?php echo strtolower($this->searchType);?>">
                        <?php endif;?>
                    </div>
                    <div class="col-xs-1">
                        <button class="btn btn-success" type="submit">
                            &nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-search"></span>
                            &nbsp;&nbsp;&nbsp;
                        </button>
                    </div>
                </div> <!-- /text input -->
            </form> <!-- /form -->
        </div>
    </div>
</div> <!-- /serch bar container -->
<!-- Dummy stuff -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-xs-12">&nbsp;</div>
    </div>
</div>
<!-- Dummy stuff -->