
<?php include 'searchbar.mobile.phtml' ?>
<!-- /Search bar -->

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <img width="40px" height="40px" style="padding: 4px" src="<?php echo $this->baseUrl(); ?>/images/noPhoto.png"/>
                        &nbsp;<?php echo $this->title; ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php if ($this->gutenContent === NULL || $this->gutenContent === "") : ?>
                    <div class="jumbotron">
                        <h3>Something went wrong!</h3>
                    </div>
                    <?php else :?>
                    <?php echo $this->gutenContent; ?>
                <?php endif;?>
                </div>
            </div>
        </div>
    </div>
    
</div>
