<div class="container">
    <!-- Dummy stuff -->
    <div class="row">
        <div class="col-xs-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-xs-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-xs-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-xs-12">&nbsp;</div>
    </div>   
    <!-- /Dummy stuff -->
    
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        Offline Library where you search for articles, books and videos from Wikipedia, Gutenberg and YouTube while offline
                    </h4> <!-- panel heading-->
                </div>
                <div class="panel-body ">
                    <form action="/search" role="search" method="GET" id="search">
                        <div class="row">
                            <div class="col-xs-9">
                                <input type="text" class="typeahead form-control" name="q" placeholder="Search for...">
                            </div>
                            <div class="col-xs-1">
                                <button class="btn btn-success" type="submit">
                                    &nbsp;&nbsp;&nbsp;
                                    <span class="glyphicon glyphicon-search"></span>
                                    &nbsp;&nbsp;&nbsp;
                                </button>
                            </div>
                        </div> <!-- /text input -->
                    </form> <!-- /form -->
                </div> <!-- /panel body-->
            </div> <!-- /panel -->
        </div> <!-- /wrapping column -->
    </div> <!-- /row -->
</div> <!-- /body container -->